### PR TITLE
Fixing for windows

### PR DESCRIPTION
**Pull request by Swat-SomeBug**

### CODE REVIEW

**Comment by Swat-SomeBug** [comment]
@boris-kolpackov could you kindly help with an issue I'm facing while disabling building static libs on windows?
`build-exclude` doesn't seem to disabling the builds on [ci.cppget.org](https://ci.cppget.org/@cd916c5e-a09f-4a7f-99b1-dc70a4cbbee2).

**Comment by boris-kolpackov** [comment]
I would recommend using the higher-level build classes to achieve this:

https://build2.org/bpkg/doc/build2-package-manager-manual.xhtml#manifest-package-builds

I think something like this should do the trick:

```
builds: default
builds: -( +windows &static ) 
```

**Comment by Swat-SomeBug** [comment]
@boris-kolpackov thanks for the quick reply. I tried it out, but it does not work.
I launched the CI task using the following command (as I'm on staged build and wanted to launch on non-staged CI)
```bash
bdep ci --builds windows --server https://ci.cppget.org
```
https://ci.cppget.org/@484bcc95-140e-47ce-8a0c-32c36958ff76

**Comment by boris-kolpackov** [comment]
You've overriden the `builds` value in the `manifest` with the `--builds` option. See https://build2.org/stage/bdep/doc/bdep-ci.xhtml

Try without one or replicate the `builds` expression in the manifest in the option value.

**Comment by Swat-SomeBug** [comment]
@boris-kolpackov Aah, ok I get it. I somehow had a different idea about the command line switch.
It seems to work. Thanks a lot!
https://ci.cppget.org/@fccc4a20-b340-4437-9806-de9daa6c1bac?builds

**Pull request merged**
